config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :experiences
  resources :qualifications
  resources :addresses
  resources :contacts
  resources :profiles
  get 'Home', to: 'main_page#index', :controller =>'maing_page'
  root 'main_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qualification.rb
class Qualification < ApplicationRecord
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:institution, :fieldofStudy, :qualificationType, :completed, :lengthofQualificatin, :yearOfStudy)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/views/qualifications/_form.html.erb
<%= form_with(model: qualification, local: true) do |form| %>
  <% if qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :fieldofStudy %>
    <%= form.text_field :fieldofStudy %>
  </div>

  <div class="field">
    <%= form.label :qualificationType %>
    <%= form.text_field :qualificationType %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="field">
    <%= form.label :lengthofQualificatin %>
    <%= form.text_field :lengthofQualificatin %>
  </div>

  <div class="field">
    <%= form.label :yearOfStudy %>
    <%= form.text_field :yearOfStudy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>Institution</th>
      <th>Fieldofstudy</th>
      <th>Qualificationtype</th>
      <th>Completed</th>
      <th>Lengthofqualificatin</th>
      <th>Yearofstudy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
        <td><%= qualification.institution %></td>
        <td><%= qualification.fieldofStudy %></td>
        <td><%= qualification.qualificationType %></td>
        <td><%= qualification.completed %></td>
        <td><%= qualification.lengthofQualificatin %></td>
        <td><%= qualification.yearOfStudy %></td>
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institution:</strong>
  <%= @qualification.institution %>
</p>

<p>
  <strong>Fieldofstudy:</strong>
  <%= @qualification.fieldofStudy %>
</p>

<p>
  <strong>Qualificationtype:</strong>
  <%= @qualification.qualificationType %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @qualification.completed %>
</p>

<p>
  <strong>Lengthofqualificatin:</strong>
  <%= @qualification.lengthofQualificatin %>
</p>

<p>
  <strong>Yearofstudy:</strong>
  <%= @qualification.yearOfStudy %>
</p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>