config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :experiences
  resources :qualifications
  resources :addresses
  resources :contacts
  resources :profiles
  get 'Home', to: 'main_page#index', :controller =>'maing_page'
  root 'main_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController

   
        def index
            @profiles = Profile.all
            @addresses = Address.all 
            @experiences = Experience.all
            @skills = Skill.all
            @qualifications = Qualification.all
            @addresses = Address.all
        end

end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/_address_section.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>
<%if @addresses.blank? %>
<h3>Please add an address</h3>
<%= link_to 'Add address', new_address_path %>
<%else%>
<table>
  <thead>
    <tr>
      <th>Addresstype</th>
      <th>Addressdetail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.addressType %></td>
        <td><%= address.addressDetail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%end%>

app/views/main_page/_contacts_section.html.erb
<h1>Contacts</h1>

<%if @contacts.blank? %>
<h3>Please add an address</h3>
<%= link_to 'Edit contact info', new_contact_path %>
<%else%>
<table>
  <thead>
    <tr>
      <th>Contacttype</th>
      <th>Contactbody</th>
    
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.contactType %></td>
        <td><%= contact.contactBody %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%end%>

app/views/main_page/_experience_section.html.erb
<%if @experiences.blank? %>
    <h3> Add your work experience</h3>
    <%= link_to 'Add Experience', new_experience_path %>
<%else%>

<h1>Work Experience</h1>

<table>
  <thead>
    <tr>
      <th>Organisation</th>
      <th>Jobtitle</th>
      <th>Startdate</th>
      <th>Enddate</th>
     
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.organisation %></td>
        <td><%= experience.jobTitle %></td>
        <td><%= experience.startDate %></td>
        <td><%= experience.endDate %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%end%>

app/views/main_page/_profile_section.html.erb
<div class= 'profile section'>


    <h1>Profiles</h1>

    <table>
    <thead>
        <tr>
        <th>Firstname</th>
        <th>Surname</th>
        <th>Gender</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @profiles.each do |profile| %>
        <tr>
            <td><%= profile.firstname %></td>
            <td><%= profile.surname %></td>
            <td><%= profile.gender %></td>
            
        </tr>
        <% end %>
    </tbody>
    </table>

    <br>

    <%= link_to 'New Profile', new_profile_path %>


</div>

app/views/main_page/_skills_section.html.erb
<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Skillname</th>
      <th>Skill</th>
      <th>Description</th>
      
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.skillName %></td>
        <td><%= skill.skill %></td>
        <td><%= skill.description %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/main_page/index.html.erb
<%=render 'profile_section'%>

<%=render 'address_section'%>

<%= render 'contacts_section'%>

<%=render 'qualifications_section'%>

<%=render 'experience_section'%>

<%= render 'skills_section'%>